In [ ]:
import numpy as np# We recommend to use numpy arrays
from os.path import isfile
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import IsolationForest
import pandas as pd # for using pandas daraframe
from sklearn.preprocessing import StandardScaler # for standardizing the Data
from sklearn.feature_selection import GenericUnivariateSelect, f_regression
from sklearn.ensemble import RandomForestRegressor
from sklearn.decomposition import PCA
from sklearn.base import BaseEstimator
class model (BaseEstimator):

    
    def __init__(self):
        '''
        This constructor is supposed to initialize data members.
        Use triple quotes for function documentation. 
        '''
        self.num_train_samples= 38563
        self.num_feat=59
        self.num_labels=1
        self.is_trained=False
        self.preprocess = GenericUnivariateSelect(f_regression, 'k_best', param=self.num_feat)
        self.mod = RandomForestRegressor(n_estimators=110, max_depth = 30,min_samples_split=5) 
    
    def fit(self, X, y):
        '''
        This function should train the model parameters.
        Here we do nothing in this example...
        Args:
            X: Training data matrix of dim num_train_samples * num_feat.
            y: Training label matrix of dim num_train_samples * num_labels.
        Both inputs are numpy arrays.
        For classification, labels could be either numbers 0, 1, ... c-1 for c classe
        or one-hot encoded vector of zeros, with a 1 at the kth position for class k.
        The AutoML format support on-hot encoding, which also works for multi-labels problems.
        Use data_converter.convert_to_num() to convert to the category number format.
        For regression, labels are continuous values.
        '''
        norm = np.linalg.norm(X)
        pca = PCA(0.99)
        pca.fit(X/norm)
        x_pca =pca. transform(X/norm)
        print(pca)
        if (not self.is_trained):
            self.num_feat = pca.n_components_
        X_preprocess=self.preprocess.fit_transform(X,y)
        print(X_preprocess)
        self.mod.fit(X_preprocess, y)
        print(y)
        self.is_trained = True
        
    def predict(self, X):
        '''
        This function should provide predictions of labels on (test) data.
        Here we just return zeros...
        Make sure that the predicted values are in the correct format for the scoring
        metric. For example, binary classification problems often expect predictions
        in the form of a discriminant value (if the area under the ROC curve it the metric)
        rather that predictions of the class labels themselves. For multi-class or multi-labels
        problems, class probabilities are often expected if the metric is cross-entropy.
        Scikit-learn also has a function predict-proba, we do not require it.
        The function predict eventually can return probabilities.
        '''
    
        y=np.random.rand(y)
        X_preprocess = self.preprocess.fit_transform(X,y)
        y = self.mod.predict(X)


        return y

    def save(self, path="./"):
        pass

    def load(self, path="./"):
        pass


def test():
    mod = model()
    X_random = np.random.rand(mod.num_train_samples,mod.num_feat)
    Y_random = np.random.rand(mod.num_train_samples,)
    
  
    mod.fit(X_random,Y_random)
    mod.predict(X_random)
    # 1 - créer un data X_random et y_random fictives: utiliser https://docs.scipy.org/doc/numpy-1.14.0/reference/generated/numpy.random.rand.html
    # 2 - Tester l'entrainement avec mod.fit(X_random, y_random)
    # 3 - Test la prediction: mod.predict(X_random)
    # Pour tester cette fonction *test*, il suffit de lancer la commande ```python sample_code_submission/model.py```

if __name__ == "__main__":
    test()

PCA(copy=True, iterated_power='auto', n_components=0.99, random_state=None,
    svd_solver='auto', tol=0.0, whiten=False)
[[0.75410028 0.30301895 0.98900366 ... 0.12811239 0.77311868 0.36164292]
 [0.23510662 0.26102436 0.27206591 ... 0.08188797 0.19414409 0.02080114]
 [0.9062137  0.60689342 0.27131143 ... 0.59153258 0.70880673 0.93681247]
 ...
 [0.81797223 0.35114514 0.71417223 ... 0.57409024 0.32069783 0.22534563]
 [0.09913789 0.70381395 0.58967634 ... 0.01240956 0.33986336 0.4661396 ]
 [0.97154176 0.17249508 0.46089476 ... 0.35721551 0.89477279 0.57620694]]


In [15]:
y=np.random.rand(3,)
y

array([0.24767169, 0.85099997, 0.92406719])